services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: blagajna
      POSTGRES_PASSWORD: blagajna
      POSTGRES_DB: blagajna
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5433:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://blagajna:blagajna@db:5432/blagajna
    ports:
      - "0.0.0.0:8081:80"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "0.0.0.0:3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:
